### ISSUE TITLE
Query string affects route

### ISSUE THREAD

**Issue by alfreb** [hioa-cs/http#4]
When accessing the default route with a query string added we get a 404. 

**Reproduce:**
- `http://trident3.vlab.cs.hioa.no:8081` => OK
- `http://trident3.vlab.cs.hioa.no:8081/?asdf=asdf` => 404 Page Not Found

**Comment by RicoAntonioFelix** [comment]
Since the `Router` is moved from this repo into the web appliance repo, this issue can now be closed.
